import { createContext, useContext, useState } from 'react';

export const LANGUAGES = [
  { code: 'English', label: 'English', native: 'English', flag: '🇮🇳', speechLang: 'en-IN' },
  { code: 'Hindi', label: 'Hindi', native: 'हिन्दी', flag: '🇮🇳', speechLang: 'hi-IN' },
  { code: 'Marathi', label: 'Marathi', native: 'मराठी', flag: '🇮🇳', speechLang: 'mr-IN' },
];

const DICTIONARY = {
  English: {
    // Brand & Header
    portalTitle: 'BIS Standard Compliance & Analytics Portal',
    portalShortTitle: 'ManakSetu',
    motto: 'मानक: पथप्रदर्शक: • Bureau of Indian Standards',
    enterpriseBadge: 'Enterprise Portal',
    activeStandards: 'Standards',
    activeCount: 'Active Standards',
    modelLabel: 'AI Engine',
    modelName: 'Gemini 2.5 Flash',
    selectLanguage: 'Select Portal Language',
    repositoryTitle: 'Standards Selector',
    repositorySubtitle: 'Filter active query scope',
    sidebarSelectAll: 'Select All Standards',
    sidebarClearAll: 'Clear Selection',
    sidebarSelectedCount: 'selected',
    noDocsYet: 'No standards indexed',
    noDocsSubtitle: 'Ensure official standard PDFs are loaded in repository.',
    indexedReady: 'Indexed',
    removeDoc: 'Remove Standard',
    textAggregator: 'Multi-Document Filter Active',

    // 6 Crisp Tab Names
    tab_standards: 'Standards',
    tab_gap_analysis: 'Gap Analysis',
    tab_summary: 'Summary',
    tab_penalties: 'Penalties',
    tab_cml_scanner: 'CM/L Scanner',
    tab_analytics: 'Analytics',

    // Tab Descriptions
    tab_standards_desc: 'Search official BIS standards or upload custom documents',
    tab_gap_desc: 'Review product technical specs against mandatory limits',
    tab_summary_desc: 'Generate executive regulatory digest across standards',
    tab_penalties_desc: 'Assess legal liabilities under BIS Act 2016',
    tab_cml_desc: 'Inspect product labels and verify CM/L license authenticity',
    tab_analytics_desc: 'Compliance health KPIs and regulatory telemetry',

    // Search Modes & Q&A
    searchModeBis: 'BIS Knowledge Base',
    searchModeUpload: 'Upload & Query',
    searchBannerTitle: 'Indian Standards Regulatory Search',
    searchBannerDesc: 'Query official BIS standards with clause citations, tolerances, and direct PDF navigation, or upload custom documents for ad-hoc analysis.',
    searchPlaceholder: 'Ask a compliance question (e.g. Clause 4.2 microbiological limits in IS 14543)...',
    customSearchPlaceholder: 'Ask a question about this uploaded document...',
    quickPromptsTitle: 'Standard Compliance Queries',
    btnAnalyze: 'Analyze Compliance',
    btnAnalyzing: 'Analyzing...',
    documentScopeLabel: 'Document Scope',
    allStandardsDefault: 'All Selected Standards',
    readAloud: '🔊 Read Aloud',
    stopAudio: '⏹ Stop Audio',
    listening: 'Listening...',
    micNotSupported: 'Speech recognition is not supported in this browser. Please use Google Chrome or Microsoft Edge.',

    // Custom Mode
    dropCustomPdf: 'Drop custom PDF here or click to browse',
    btnRunCustom: 'Analyze Custom Document',
    customReady: 'Document ready for AI interrogation',

    // Gap Analysis Tab
    gapBannerTitle: 'Predictive Tech Specs Gap Analysis',
    gapBannerDesc: 'Evaluate proposed or measured product technical specifications against official Bureau of Indian Standards limits. Identify violations before statutory submission.',
    specsInputLabel: 'Product Technical Specifications',
    specsPlaceholder: 'Enter or paste specifications (e.g. Voltage: 240V, Operating Temp: 55°C, TDS: 450 mg/L, Total Coliforms: Nil)...',
    samplePresetsTitle: 'Load Industry Sample Specs',
    btnRunGapAnalysis: 'Evaluate Technical Specs',
    btnEvaluating: 'Evaluating Compliance...',
    gapOverallStatus: 'Overall Compliance Verdict',
    gapComplianceScore: 'Statutory Score',
    gapSummaryTitle: 'Executive Gap Analysis Summary',
    paramTableTitle: 'Parameter Compliance Heatmap',
    colParam: 'Parameter',
    colUserVal: 'Submitted Value',
    colBisLimit: 'BIS Standard Limit',
    colStatus: 'Status',
    colClause: 'Standard Clause',
    colObservation: 'Technical Finding & Remedy',
    statusPass: 'PASS',
    statusWarning: 'WARNING',
    statusFail: 'FAIL',
    statusCompliant: 'COMPLIANT',
    statusNonCompliant: 'NON-COMPLIANT',
    statusReview: 'NEEDS REVIEW',

    // Summary Tab
    summaryBannerTitle: 'Executive Compliance Digest',
    summaryBannerDesc: 'Synthesize selected BIS standards into an executive briefing with mandatory obligations, testing protocols, and applicability matrix.',
    btnGenerateSummary: 'Generate Executive Digest',
    btnSynthesizing: 'Synthesizing Standards...',
    featureMandatory: 'Mandatory Clauses',
    featureMandatoryDesc: 'Identifies critical statutory rules across all active standards.',
    featureLab: 'Lab Testing Protocols',
    featureLabDesc: 'Extracts batch testing, sampling schemes, and lab tolerances.',
    featureMatrix: 'Cross-Standard Matrix',
    featureMatrixDesc: 'Unified compliance footprint for multi-product operations.',

    // Penalties Tab
    penaltiesBannerTitle: 'Statutory Penalties & Legal Risk Assessment',
    penaltiesBannerDesc: 'Extract statutory penalties, imprisonment terms, fine structures, and non-compliance liabilities under Section 29 & 30 of the BIS Act 2016.',
    btnExtractPenalties: 'Extract Legal Penalties',
    btnEvaluatingRisk: 'Evaluating Risk...',
    penaltyImprisonment: 'Imprisonment & Fines',
    penaltyImprisonmentDesc: 'Offences under Section 29 carrying up to 2 years prison or ₹5 Lakhs+ fine.',
    penaltyCompounding: 'Compounding & Seizures',
    penaltyCompoundingDesc: 'Powers of search, product seizure, and recall provisions.',
    penaltyMitigation: 'Risk Mitigation',
    penaltyMitigationDesc: 'Actionable steps to insulate manufacturing operations.',

    // CM/L Scanner Tab
    cmlBannerTitle: 'BIS Standard Mark & CM/L License Scanner',
    cmlBannerDesc: 'Inspect product packaging photographs, extract CM/L license codes using Vision AI, and verify authenticity against the BIS registry.',
    btnBrowseRegistry: 'Browse CM/L Registry',
    btnHideRegistry: 'Hide Registry',
    dropImageText: 'Upload Product Label or ISI Mark Photo',
    dropImageSubtitle: 'PNG, JPEG, WebP (Photo of product packaging or license certificate)',
    btnVerifyCml: 'Verify License Authenticity',
    btnVerifyingCml: 'Verifying with Vision OCR...',
    cmlOutcome: 'Registry Verification Outcome',
    cmlExtractedNo: 'Extracted CM/L Number',
    cmlManufacturer: 'Manufacturer',
    cmlStandard: 'Standard Specification',
    cmlDbMatch: 'Registry Confirmation',
    cmlOfficialRecord: 'Official BIS Registry Record',
    cmlVisionNotes: 'Vision OCR Technical Findings',
    statusValid: 'VALID & ACTIVE',
    statusExpired: 'LICENSE EXPIRED',
    statusSuspended: 'LICENSE SUSPENDED',
    statusUnregistered: 'NOT FOUND IN REGISTRY',
    confirmedDb: 'Confirmed in Registry',
    notInDb: 'No Direct Registry Match',

    // Analytics Dashboard
    analyticsBannerTitle: 'Compliance & Audit Analytics Dashboard',
    analyticsBannerDesc: 'Cross-standard clause distribution, risk tier breakdowns, monthly verification trends, and license registry telemetry.',
    kpiTotalStandards: 'Active Standards',
    kpiTotalPages: 'Pages Indexed',
    kpiClausesAnalyzed: 'Clauses Indexed',
    kpiAvgHealth: 'Compliance Readiness',
    kpiCmlLicenses: 'Tracked CM/L Licenses',
    chartMonthlyTitle: 'Monthly Query & Verification Volume',
    chartMonthlySub: 'Compliance searches vs CM/L label scans',
    chartSectorTitle: 'Industry Sector Coverage',
    chartSectorSub: 'Distribution across Indian Standards',
    chartRiskTitle: 'Clause Risk Tier & Liability Breakdown',
    chartRiskSub: 'Statutory penalty weight and mandatory testing allocation',
    catalogTitle: 'Active Standards Catalog',
    colDoc: 'Standard Document',
    colCategory: 'Category',
    colPages: 'Pages',
    colChars: 'Characters',
    colClauses: 'Clauses',
    colReadiness: 'Readiness Index',

    // Common Actions & Export
    btnPdfReport: 'PDF Report',
    btnExcelSheet: 'Excel Sheet',
    btnCopy: 'Copy',
    btnCopied: 'Copied',
    btnRetry: 'Retry',
    citationNotice: 'Click highlighted citations to jump directly to official standard clauses.',
    auditHeader: 'Bureau of Indian Standards Compliance Audit',
    noDocsWarningTitle: 'No BIS Standard Documents Selected',
    noDocsWarningDesc: 'Please select one or more standard documents in the left sidebar selector.',
  },

  Hindi: {
    // Brand & Header
    portalTitle: 'बीआईएस मानक अनुपालन एवं एनालिटिक्स पोर्टल',
    portalShortTitle: 'ManakSetu',
    motto: 'मानक: पथप्रदर्शक: • भारतीय मानक ब्यूरो',
    enterpriseBadge: 'एंटरप्राइज पोर्टल',
    activeStandards: 'मानक',
    activeCount: 'सक्रिय मानक',
    modelLabel: 'एआई इंजन',
    modelName: 'जेमिनी 2.5 फ्लैश',
    selectLanguage: 'पोर्टल भाषा चुनें',
    repositoryTitle: 'मानक चयनकर्ता',
    repositorySubtitle: 'सक्रिय खोज दायरा चुनें',
    sidebarSelectAll: 'सभी मानक चुनें',
    sidebarClearAll: 'चयन साफ़ करें',
    sidebarSelectedCount: 'चयनित',
    noDocsYet: 'कोई मानक उपलब्ध नहीं',
    noDocsSubtitle: 'सुनिश्चित करें कि आधिकारिक मानक पीडीएफ उपलब्ध हैं।',
    indexedReady: 'अनुक्रमित',
    removeDoc: 'मानक हटाएं',
    textAggregator: 'मल्टी-डॉक्यूमेंट फ़िल्टर सक्रिय',

    // 6 Crisp Tab Names
    tab_standards: 'मानक',
    tab_gap_analysis: 'गैप विश्लेषण',
    tab_summary: 'सारांश',
    tab_penalties: 'दंड',
    tab_cml_scanner: 'CM/L स्कैनर',
    tab_analytics: 'एनालिटिक्स',

    // Tab Descriptions
    tab_standards_desc: 'आधिकारिक बीआईएस मानकों की खोज करें या कस्टम दस्तावेज अपलोड करें',
    tab_gap_desc: 'अनिवार्य सीमाओं के विरुद्ध उत्पाद विनिर्देशों की समीक्षा',
    tab_summary_desc: 'मानकों का कार्यकारी सारांश तैयार करें',
    tab_penalties_desc: 'बीआईएस अधिनियम 2016 के तहत कानूनी जोखिमों का आकलन',
    tab_cml_desc: 'उत्पाद लेबल जांचें और CM/L लाइसेंस की पुष्टि करें',
    tab_analytics_desc: 'अनुपालन स्वास्थ्य मेट्रिक्स और विनियामक टेलीमेट्री',

    // Search Modes & Q&A
    searchModeBis: 'बीआईएस ज्ञान आधार',
    searchModeUpload: 'अपलोड और खोज',
    searchBannerTitle: 'भारतीय मानक विनियामक खोज',
    searchBannerDesc: 'सटीक खंड उद्धरणों के साथ बीआईएस मानक खोजें या कस्टम पीडीएफ विश्लेषण करें।',
    searchPlaceholder: 'अनुपालन प्रश्न पूछें (उदा. IS 14543 में खंड 4.2 माइक्रोबायोलॉजिकल सीमाएं)...',
    customSearchPlaceholder: 'इस दस्तावेज़ के बारे में प्रश्न पूछें...',
    quickPromptsTitle: 'त्वरित विनियामक प्रश्न',
    btnAnalyze: 'अनुपालन विश्लेषण करें',
    btnAnalyzing: 'विश्लेषण जारी...',
    documentScopeLabel: 'दस्तावेज़ दायरा',
    allStandardsDefault: 'सभी चयनित मानक',
    readAloud: '🔊 जोर से पढ़ें',
    stopAudio: '⏹ बोलना बंद करें',
    listening: 'सुन रहा है...',
    micNotSupported: 'इस ब्राउज़र में स्पीच रिकग्निशन समर्थित नहीं है।',

    // Custom Mode
    dropCustomPdf: 'कस्टम पीडीएफ यहां डालें या ब्राउज़ करें',
    btnRunCustom: 'कस्टम विश्लेषण करें',
    customReady: 'दस्तावेज़ विश्लेषण के लिए तैयार',

    // Gap Analysis Tab
    gapBannerTitle: 'पूर्वानुमानित तकनीकी विनिर्देश गैप विश्लेषण',
    gapBannerDesc: 'बीआईएस मानक सीमाओं के विरुद्ध प्रस्तावित तकनीकी विनिर्देशों का मूल्यांकन करें।',
    specsInputLabel: 'उत्पाद तकनीकी विनिर्देश',
    specsPlaceholder: 'विनिर्देश दर्ज करें (उदा. वोल्टेज: 240V, ऑपरेटिंग तापमान: 55°C)...',
    samplePresetsTitle: 'उद्योग नमूना विनिर्देश लोड करें',
    btnRunGapAnalysis: 'विनिर्देशों का मूल्यांकन करें',
    btnEvaluating: 'मूल्यांकन जारी...',
    gapOverallStatus: 'समग्र अनुपालन निर्णय',
    gapComplianceScore: 'वैधानिक स्कोर',
    gapSummaryTitle: 'कार्यकारी गैप विश्लेषण सारांश',
    paramTableTitle: 'पैरामीटर अनुपालन हीटमैप',
    colParam: 'पैरामीटर',
    colUserVal: 'प्रस्तुत मान',
    colBisLimit: 'बीआईएस मानक सीमा',
    colStatus: 'स्थिति',
    colClause: 'मानक खंड',
    colObservation: 'तकनीकी निष्कर्ष एवं उपाय',
    statusPass: 'पास',
    statusWarning: 'चेतावनी',
    statusFail: 'फेल',
    statusCompliant: 'अनुपालक (पास)',
    statusNonCompliant: 'गैर-अनुपालक (फेल)',
    statusReview: 'समीक्षा आवश्यक',

    // Summary Tab
    summaryBannerTitle: 'व्यापक कार्यकारी अनुपालन सारांश',
    summaryBannerDesc: 'चयनित बीआईएस मानकों को अनिवार्य दायित्वों और परीक्षण प्रोटोकॉल के साथ संक्षिप्त करें।',
    btnGenerateSummary: 'कार्यकारी सारांश बनाएं',
    btnSynthesizing: 'संश्लेषण जारी...',
    featureMandatory: 'अनिवार्य खंड',
    featureMandatoryDesc: 'सभी सक्रिय मानकों में महत्वपूर्ण वैधानिक नियमों की पहचान।',
    featureLab: 'प्रयोगशाला परीक्षण प्रोटोकॉल',
    featureLabDesc: 'बैच परीक्षण और सहनशीलता सीमाएं।',
    featureMatrix: 'क्रॉस-मानक मैट्रिक्स',
    featureMatrixDesc: 'बहु-उत्पाद संचालन के लिए एकीकृत अनुपालन ढांचा।',

    // Penalties Tab
    penaltiesBannerTitle: 'वैधानिक दंड एवं कानूनी जोखिम मूल्यांकन',
    penaltiesBannerDesc: 'बीआईएस अधिनियम 2016 की धारा 29 और 30 के तहत कानूनी दंड निकालें।',
    btnExtractPenalties: 'कानूनी दंड निकालें',
    btnEvaluatingRisk: 'जोखिम मूल्यांकन जारी...',
    penaltyImprisonment: 'कारावास एवं जुर्माना',
    penaltyImprisonmentDesc: 'धारा 29 के तहत 2 वर्ष तक का कारावास या ₹5 लाख+ जुर्माना।',
    penaltyCompounding: 'जब्ती एवं अधिकार',
    penaltyCompoundingDesc: 'तलाशी और उत्पाद जब्ती के अधिकार।',
    penaltyMitigation: 'जोखिम शमन',
    penaltyMitigationDesc: 'निर्माण कार्यों को सुरक्षित रखने के व्यावहारिक कदम।',

    // CM/L Scanner Tab
    cmlBannerTitle: 'बीआईएस मानक मार्क एवं CM/L लाइसेंस स्कैनर',
    cmlBannerDesc: 'उत्पाद पैकेजिंग की तस्वीरों का निरीक्षण करें और CM/L कोड सत्यापित करें।',
    btnBrowseRegistry: 'रजिस्ट्री डेटाबेस देखें',
    btnHideRegistry: 'रजिस्ट्री छिपाएं',
    dropImageText: 'उत्पाद लेबल या आईएसआई मार्क फोटो अपलोड करें',
    dropImageSubtitle: 'PNG, JPEG, WebP',
    btnVerifyCml: 'लाइसेंस प्रामाणिकता सत्यापित करें',
    btnVerifyingCml: 'विज़न ओसीआर सत्यापन जारी...',
    cmlOutcome: 'रजिस्ट्री सत्यापन परिणाम',
    cmlExtractedNo: 'निकाला गया CM/L नंबर',
    cmlManufacturer: 'निर्माता',
    cmlStandard: 'मानक विनिर्देश',
    cmlDbMatch: 'रजिस्ट्री पुष्टि',
    cmlOfficialRecord: 'आधिकारिक बीआईएस रजिस्ट्री विवरण',
    cmlVisionNotes: 'विज़न ओसीआर टिप्पणियां',
    statusValid: 'मान्य एवं सक्रिय',
    statusExpired: 'लाइसेंस समाप्त',
    statusSuspended: 'लाइसेंस निलंबित',
    statusUnregistered: 'रजिस्ट्री में नहीं मिला',
    confirmedDb: 'रजिस्ट्री में पुष्टि हुई',
    notInDb: 'रजिस्ट्री में कोई सीधा मिलान नहीं',

    // Analytics Dashboard
    analyticsBannerTitle: 'अनुपालन एवं ऑडिट एनालिटिक्स डैशबोर्ड',
    analyticsBannerDesc: 'क्रॉस-मानक खंड वितरण और लाइसेंस रजिस्ट्री टेलीमेट्री।',
    kpiTotalStandards: 'सक्रिय मानक',
    kpiTotalPages: 'अनुक्रमित पृष्ठ',
    kpiClausesAnalyzed: 'अनुक्रमित खंड',
    kpiAvgHealth: 'अनुपालन तत्परता',
    kpiCmlLicenses: 'ट्रैक किए गए CM/L लाइसेंस',
    chartMonthlyTitle: 'मासिक प्रश्न एवं सत्यापन मात्रा',
    chartMonthlySub: 'अनुपालन खोज बनाम CM/L लेबल स्कैन',
    chartSectorTitle: 'उद्योग क्षेत्र कवरेज',
    chartSectorSub: 'भारतीय मानकों में वितरण',
    chartRiskTitle: 'खंड जोखिम स्तर विभाजन',
    chartRiskSub: 'वैधानिक दंड भार',
    catalogTitle: 'सक्रिय मानक कैटलॉग',
    colDoc: 'मानक दस्तावेज़',
    colCategory: 'श्रेणी',
    colPages: 'पृष्ठ',
    colChars: 'अक्षर',
    colClauses: 'खंड',
    colReadiness: 'तत्परता सूचकांक',

    // Common Actions & Export
    btnPdfReport: 'पीडीएफ रिपोर्ट',
    btnExcelSheet: 'एक्सेल शीट',
    btnCopy: 'कॉपी',
    btnCopied: 'कॉपी हो गया',
    btnRetry: 'पुनः प्रयास',
    citationNotice: 'आधिकारिक मानक खंडों पर जाने के लिए संदर्भों पर क्लिक करें।',
    auditHeader: 'भारतीय मानक ब्यूरो अनुपालन ऑडिट',
    noDocsWarningTitle: 'कोई मानक चुना नहीं गया',
    noDocsWarningDesc: 'कृपया पहले बाईं ओर साइडबार में एक या अधिक मानक चुनें।',
  },

  Marathi: {
    // Brand & Header
    portalTitle: 'बीआयएस मानक अनुपालन आणि ॲनालिटिक्स पोर्टल',
    portalShortTitle: 'ManakSetu',
    motto: 'मानक: पथप्रदर्शक: • भारतीय मानक ब्युरो',
    enterpriseBadge: 'एंटरप्राइज पोर्टल',
    activeStandards: 'मानके',
    activeCount: 'सक्रिय मानके',
    modelLabel: 'एआय इंजिन',
    modelName: 'जेमिनी 2.5 फ्लॅश',
    selectLanguage: 'पोर्टल भाषा निवडा',
    repositoryTitle: 'मानक निवडक',
    repositorySubtitle: 'सक्रिय शोध व्याप्ती निवडा',
    sidebarSelectAll: 'सर्व मानके निवडा',
    sidebarClearAll: 'निवड साफ करा',
    sidebarSelectedCount: 'निवडलेले',
    noDocsYet: 'कोणतेही मानक उपलब्ध नाही',
    noDocsSubtitle: 'अधिकृत मानक पीडीएफ उपलब्ध असल्याची खात्री करा.',
    indexedReady: 'अनुक्रमित',
    removeDoc: 'मानक काढा',
    textAggregator: 'मल्टी-डॉक्युमेंट फिल्टर सक्रिय',

    // 6 Crisp Tab Names
    tab_standards: 'मानके',
    tab_gap_analysis: 'गॅप विश्लेषण',
    tab_summary: 'सारांश',
    tab_penalties: 'दंड',
    tab_cml_scanner: 'CM/L स्कॅनर',
    tab_analytics: 'ॲनालिटिक्स',

    // Tab Descriptions
    tab_standards_desc: 'अधिकृत बीआयएस मानके शोधा किंवा कस्टम दस्तऐवज अपलोड करा',
    tab_gap_desc: 'अनिवार्य मर्यादांविरूद्ध तांत्रिक तपशीलांचे पुनरावलोकन',
    tab_summary_desc: 'मानकांचा कार्यकारी सारांश तयार करा',
    tab_penalties_desc: 'बीआयएस कायदा 2016 अंतर्गत कायदेशीर जोखीम मूल्यांकन',
    tab_cml_desc: 'उत्पादन लेबल तपासा आणि CM/L परवाना पडताळा',
    tab_analytics_desc: 'अनुपालन आरोग्य मेट्रिक्स आणि नियामक टेलिमेट्री',

    // Search Modes & Q&A
    searchModeBis: 'बीआयएस ज्ञान आधार',
    searchModeUpload: 'अपलोड आणि शोध',
    searchBannerTitle: 'भारतीय मानक नियामक शोध',
    searchBannerDesc: 'अचूक कलम संदर्भांसह बीआयएस मानके शोधा किंवा कस्टम पीडीएफचे विश्लेषण करा.',
    searchPlaceholder: 'अनुपालन प्रश्न विचारा (उदा. IS 14543 मधील कलम 4.2 सूक्ष्मजीव मर्यादा)...',
    customQueryPlaceholder: 'या दस्तऐवजाबद्दल प्रश्न विचारा...',
    quickPromptsTitle: 'द्रुत नियामक प्रश्न',
    btnAnalyze: 'अनुपालन विश्लेषण करा',
    btnAnalyzing: 'विश्लेषण सुरू आहे...',
    documentScopeLabel: 'दस्तऐवज व्याप्ती',
    allStandardsDefault: 'सर्व निवडलेली मानके',
    readAloud: '🔊 मोठ्याने वाचा',
    stopAudio: '⏹ बोलणे थांबवा',
    listening: 'ऐकत आहे...',
    micNotSupported: 'या ब्राउझरमध्ये स्पीच रेकग्निशन समर्थित नाही.',

    // Custom Mode
    dropCustomPdf: 'कस्टम पीडीएफ येथे टाका किंवा ब्राउझ करा',
    btnRunCustom: 'कस्टम विश्लेषण करा',
    customReady: 'दस्तऐवज विश्लेषणासाठी सज्ज',

    // Gap Analysis Tab
    gapBannerTitle: 'पूर्वानुमानित तांत्रिक तपशील गॅप विश्लेषण',
    gapBannerDesc: 'बीआयएस मानक मर्यादांविरूद्ध तांत्रिक तपशीलांचे मूल्यांकन करा.',
    specsInputLabel: 'उत्पादन तांत्रिक तपशील',
    specsPlaceholder: 'तपशील प्रविष्ट करा (उदा. व्होल्टेज: 240V, कमाल तापमान: 55°C)...',
    samplePresetsTitle: 'उद्योग नमुना तपशील लोड करा',
    btnRunGapAnalysis: 'तांत्रिक तपशीलांचे मूल्यांकन करा',
    btnEvaluating: 'मूल्यांकन सुरू आहे...',
    gapOverallStatus: 'एकूण अनुपालन निकाल',
    gapComplianceScore: 'वैधानिक स्कोअर',
    gapSummaryTitle: 'कार्यकारी गॅप विश्लेषण सारांश',
    paramTableTitle: 'पॅरामीटर अनुपालन हीटमॅप',
    colParam: 'पॅरामीटर',
    colUserVal: 'दिलेले मूल्य',
    colBisLimit: 'बीआयएस मानक मर्यादा',
    colStatus: 'स्थिती',
    colClause: 'मानक कलम',
    colObservation: 'तांत्रिक निष्कर्ष आणि उपाय',
    statusPass: 'पास',
    statusWarning: 'चेतावणी',
    statusFail: 'नापास',
    statusCompliant: 'अनुपालक (पास)',
    statusNonCompliant: 'गैर-अनुपालक (नापास)',
    statusReview: 'पुनरावलोकन आवश्यक',

    // Summary Tab
    summaryBannerTitle: 'सर्वसमावेशक कार्यकारी अनुपालन सारांश',
    summaryBannerDesc: 'निवडलेली बीआयएस मानके अनिवार्य दायित्वे आणि चाचणी प्रोटोकॉलसह संक्षिप्त करा.',
    btnGenerateSummary: 'कार्यकारी सारांश तयार करा',
    btnSynthesizing: 'संश्लेषण सुरू आहे...',
    featureMandatory: 'अनिवार्य कलमे',
    featureMandatoryDesc: 'सर्व सक्रिय मानकांमध्ये महत्त्वाच्या वैधानिक नियमांची ओळख.',
    featureLab: 'प्रयोगशाळा चाचणी प्रोटोकॉल',
    featureLabDesc: 'बॅच चाचणी आणि सहनशीलता मर्यादा.',
    featureMatrix: 'क्रॉस-मानक मॅट्रिक्स',
    featureMatrixDesc: 'अनेक उत्पादन ऑपरेशन्ससाठी एकत्रित अनुपालन चौकट.',

    // Penalties Tab
    penaltiesBannerTitle: 'वैधानिक दंड आणि कायदेशीर जोखीम मूल्यांकन',
    penaltiesBannerDesc: 'बीआयएस कायदा 2016 च्या कलम 29 आणि 30 अंतर्गत कायदेशीर दंड काढा.',
    btnExtractPenalties: 'कायदेशीर दंड काढा',
    btnEvaluatingRisk: 'जोखिम मूल्यांकन सुरू आहे...',
    penaltyImprisonment: 'तुरुंगवास आणि दंड',
    penaltyImprisonmentDesc: 'कलम 29 अंतर्गत 2 वर्षांपर्यंत तुरुंगवास किंवा ₹5 लाख+ दंड.',
    penaltyCompounding: 'जप्ती आणि अधिकार',
    penaltyCompoundingDesc: 'शोध आणि उत्पादन जप्तीचे अधिकार.',
    penaltyMitigation: 'जोखिम शमन',
    penaltyMitigationDesc: 'उत्पादन सुरक्षित ठेवण्यासाठी पावले.',

    // CM/L Scanner Tab
    cmlBannerTitle: 'बीआयएस मानक मार्क आणि CM/L परवाना स्कॅनर',
    cmlBannerDesc: 'उत्पादनाचे पॅकेजिंग फोटो तपासा आणि CM/L कोड पडताळा.',
    btnBrowseRegistry: 'नोंदणी डेटाबेस पहा',
    btnHideRegistry: 'नोंदणी लपवा',
    dropImageText: 'उत्पादन लेबल किंवा आयएसआय मार्क फोटो अपलोड करा',
    dropImageSubtitle: 'PNG, JPEG, WebP',
    btnVerifyCml: 'परवाना सत्यता पडताळा',
    btnVerifyingCml: 'व्हिजन ओसीआर पडताळणी सुरू आहे...',
    cmlOutcome: 'नोंदणी पडताळणी निकाल',
    cmlExtractedNo: 'काढलेला CM/L क्रमांक',
    cmlManufacturer: 'उत्पादक',
    cmlStandard: 'मानक तपशील',
    cmlDbMatch: 'नोंदणी पुष्टी',
    cmlOfficialRecord: 'अधिकृत बीआयएस नोंदणी तपशील',
    cmlVisionNotes: 'व्हिजन ओसीआर निरीक्षणे',
    statusValid: 'वैध आणि सक्रिय',
    statusExpired: 'परवाना कालबाह्य',
    statusSuspended: 'परवाना निलंबित',
    statusUnregistered: 'नोंदणीमध्ये सापडले नाही',
    confirmedDb: 'नोंदणीमध्ये पुष्टी झाली',
    notInDb: 'नोंदणीमध्ये थेट जुळणी नाही',

    // Analytics Dashboard
    analyticsBannerTitle: 'अनुपालन आणि ऑडिट ॲनालिटिक्स डॅशबोर्ड',
    analyticsBannerDesc: 'क्रॉस-मानक कलम वितरण आणि परवाना नोंदणी टेलिमेट्री.',
    kpiTotalStandards: 'सक्रिय मानके',
    kpiTotalPages: 'अनुक्रमित पृष्ठे',
    kpiClausesAnalyzed: 'अनुक्रमित कलमे',
    kpiAvgHealth: 'अनुपालन सज्जता',
    kpiCmlLicenses: 'ट्रॅक केलेले CM/L परवाने',
    chartMonthlyTitle: 'मासिक प्रश्न आणि पडताळणी प्रमाण',
    chartMonthlySub: 'अनुपालन शोध विरूद्ध CM/L लेबल स्कॅन',
    chartSectorTitle: 'उद्योग क्षेत्र कव्हरेज',
    chartSectorSub: 'भारतीय मानकांमध्ये वितरण',
    chartRiskTitle: 'कलम जोखीम स्तर विभागणी',
    chartRiskSub: 'वैधानिक दंड भार',
    catalogTitle: 'सक्रिय मानक कॅटलॉग',
    colDoc: 'मानक दस्तऐवज',
    colCategory: 'श्रेणी',
    colPages: 'पृष्ठे',
    colChars: 'अक्षरे',
    colClauses: 'कलमे',
    colReadiness: 'सज्जता निर्देशांक',

    // Common Actions & Export
    btnPdfReport: 'पीडीएफ अहवाल',
    btnExcelSheet: 'एक्सेल शीट',
    btnCopy: 'कॉपी',
    btnCopied: 'कॉपी झाले',
    btnRetry: 'पुन्हा प्रयत्न',
    citationNotice: 'अधिकृत मानक कलमांवर जाण्यासाठी संदर्भांवर क्लिक करा.',
    auditHeader: 'भारतीय मानक ब्युरो अनुपालन ऑडिट',
    noDocsWarningTitle: 'कोणतेही मानक निवडलेले नाही',
    noDocsWarningDesc: 'कृपया आधी डाव्या बाजूच्या साइडबारमध्ये एक किंवा अधिक मानके निवडा.',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('bis_portal_lang') || 'English';
  });

  const setLanguage = (langCode) => {
    setLanguageState(langCode);
    localStorage.setItem('bis_portal_lang', langCode);
  };

  const currentLangMeta = LANGUAGES.find((l) => l.code === language) || LANGUAGES[0];
  const t = DICTIONARY[language] || DICTIONARY['English'];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLangMeta, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
